    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carritocompras.Ventanas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author Arturo
 */
public class Login extends javax.swing.JFrame {
    private Connection conexionActiva;
    
    public Login(Connection conexion) {
        initComponents();
        this.conexionActiva = conexion;
    }

    /**
     * Creates new form Login
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioTXT = new javax.swing.JTextField();
        contraTXT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BInicioSesion = new javax.swing.JButton();
        BRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuarioTXT.addActionListener(this::usuarioTXTActionPerformed);

        jLabel1.setText("Bienvenido, Inicia Sesión");

        BInicioSesion.setText("Inicar Sesión");
        BInicioSesion.addActionListener(this::BInicioSesionActionPerformed);

        BRegistro.setText("Registrarse Aquí");
        BRegistro.addActionListener(this::BRegistroActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(BInicioSesion))
                        .addComponent(contraTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(usuarioTXT)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(usuarioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contraTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BInicioSesion)
                .addGap(29, 29, 29)
                .addComponent(BRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInicioSesionActionPerformed
        // TODO add your handling code here:
        String usertxt= usuarioTXT.getText();
        String passtxt= contraTXT.getText();
        //consulta a la bd
        String sql = "SELECT * FROM usuarios WHERE nombre_usuario = ? AND contra_usuario = ?";
        try {
        //consulta usando conexion que heredó la ventana
        java.sql.PreparedStatement ps = this.conexionActiva.prepareStatement(sql);
        ps.setString(1, usertxt);
        ps.setString(2, passtxt);

        //ejecutamos consulta
        java.sql.ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            //buscamos al usuario
            int idUsuarioLogueado = rs.getInt("id_usuario");
            String nombreLogueado = rs.getString("nombre_usuario");
            
            Menú VentanaMenu = new Menú(this.conexionActiva, usertxt);
            VentanaMenu.setVisible(true);
            VentanaMenu.setLocationRelativeTo(null);
 
            
            //cerramos ventana login
            this.dispose(); 
        } else {
            //error al momento de iniciar sesion
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
        }

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
    }
    }//GEN-LAST:event_BInicioSesionActionPerformed

    private void BRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistroActionPerformed
        // TODO add your handling code here:
    VentanaRegistro ventanaReg = new VentanaRegistro(this.conexionActiva);
    ventanaReg.setVisible(true);
    ventanaReg.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_BRegistroActionPerformed

    private void usuarioTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BInicioSesion;
    private javax.swing.JButton BRegistro;
    private javax.swing.JTextField contraTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField usuarioTXT;
    // End of variables declaration//GEN-END:variables
}
