/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carritocompras.Ventanas;
import java.sql.Connection;
/**
 *
 * @author Arturo
 */
public class Menú extends javax.swing.JFrame {
    private java.sql.Connection conexionActiva;
    private boolean usuario = false;
    private boolean MenuDespegable = false;
        
    public Menú(java.sql.Connection conexion, String nUsuario) {
        initComponents();
        this.conexionActiva = conexion;
        this.setLocationRelativeTo(null);
        
        PanelBarra.setVisible(false);
        if (nUsuario != null && !nUsuario.isEmpty()){
            this.usuario = true;
            BInicioSesion.setVisible(false);
            LBienvenida.setText("Bienvenido "+nUsuario  );
            LBienvenida.setVisible(true);
            
            
        }else{
            this.usuario = false;
            BInicioSesion.setVisible(true);
            LBienvenida.setVisible(false);
        }
    
    }

    /**
     * Creates new form Menú
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BInicioSesion = new javax.swing.JButton();
        LBienvenida = new javax.swing.JLabel();
        PanelBarra = new javax.swing.JPanel();
        BVenta = new javax.swing.JButton();
        BHamburguesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BInicioSesion.setText("Iniciar Sesión");
        BInicioSesion.addActionListener(this::BInicioSesionActionPerformed);

        LBienvenida.setText("jLabel2");

        PanelBarra.setBackground(new java.awt.Color(153, 153, 153));

        BVenta.setBackground(new java.awt.Color(153, 153, 153));
        BVenta.setText("Vender");
        BVenta.addActionListener(this::BVentaActionPerformed);

        javax.swing.GroupLayout PanelBarraLayout = new javax.swing.GroupLayout(PanelBarra);
        PanelBarra.setLayout(PanelBarraLayout);
        PanelBarraLayout.setHorizontalGroup(
            PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBarraLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BVenta)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        PanelBarraLayout.setVerticalGroup(
            PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarraLayout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(BVenta)
                .addGap(107, 107, 107))
        );

        BHamburguesa.setText("☰");
        BHamburguesa.addActionListener(this::BHamburguesaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHamburguesa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(BInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BInicioSesion)
                    .addComponent(LBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(BHamburguesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInicioSesionActionPerformed
        // TODO add your handling code here:
        //Instancia de ventana login con conexion
        Login VLogin = new Login(this.conexionActiva);
        //Abrimos ventana
        VLogin.setVisible(true);
        //codigo para centrar ventana en medio
        VLogin.setLocationRelativeTo(null);
        
        
        
    }//GEN-LAST:event_BInicioSesionActionPerformed

    private void BHamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHamburguesaActionPerformed
        // TODO add your handling code here:
        if (MenuDespegable){
            PanelBarra.setVisible(false);
            MenuDespegable = false;
        }else{
            PanelBarra.setVisible(true);
            MenuDespegable = true;
        }
    }//GEN-LAST:event_BHamburguesaActionPerformed

    private void BVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVentaActionPerformed
        // TODO add your handling code here:
        if (this.usuario){
            VPublicar ventanap = new VPublicar(this.conexionActiva);
                ventanap.setVisible(true);
                ventanap.setLocationRelativeTo(null); 
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Debes iniciar sesión para publicar y vender productos.");
            
            Login ventLogin = new Login (this.conexionActiva);
            ventLogin.setVisible(true);
            ventLogin.setLocationRelativeTo(null);
        }
        
        
        
    }//GEN-LAST:event_BVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHamburguesa;
    private javax.swing.JButton BInicioSesion;
    private javax.swing.JButton BVenta;
    private javax.swing.JLabel LBienvenida;
    private javax.swing.JPanel PanelBarra;
    // End of variables declaration//GEN-END:variables
}
