/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carritocompras.Ventanas;
import java.sql.Connection;
/**
 *
 * @author Arturo
 */
public class Menú extends javax.swing.JFrame {
    private java.sql.Connection conexionActiva;
    private boolean usuario = false;
    private boolean MenuDespegable = false;
        
    public Menú(java.sql.Connection conexion, String nUsuario) {
        initComponents();
        this.conexionActiva = conexion;
        this.setLocationRelativeTo(null);
        
        PanelBarra.setVisible(false);
        if (nUsuario != null && !nUsuario.isEmpty()){
            this.usuario = true;
            BInicioSesion.setVisible(false);
            LBienvenida.setText("Bienvenido "+nUsuario  );
            LBienvenida.setVisible(true);
            
            
        }else{
            this.usuario = false;
            BInicioSesion.setVisible(true);
            LBienvenida.setVisible(false);
        }
        
        cargarProductos("Todas");
    
    }
    public void cargarProductos(String categorias){
        //Limpia tarjetas anteriores
        pnlProductos.removeAll();
        
        String sql;
        if(categorias.equals("Todas")){
            sql = "SELECT * FROM productos";
        }else{
            sql = "SELECT * FROM productos WHERE carcateristica ILIKE ?"; //ILIKE se usa por si hay problemas con los nombres
        }
        try{
            java.sql.PreparedStatement ps = this.conexionActiva.prepareStatement(sql);
            if(!categorias.equals("Todas")){
                ps.setString(1, categorias);
            }
            java.sql.ResultSet rs = ps.executeQuery();
            
            //revisamos productos en la BS
            while(rs.next()){
            String nombre = rs.getString("nombre");
            double precio = rs.getDouble("precio");
            String marca = rs.getString("marca");
            int stock = rs.getInt("stock");
            
            //se crean tarjetas visuales para cada producto
            javax.swing.JPanel tarjeta = new javax.swing.JPanel();
            tarjeta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            tarjeta.setLayout(new java.awt.GridLayout(5, 1)); // 4 líneas verticalmente
            tarjeta.setPreferredSize(new java.awt.Dimension(180, 165));
            
            //componentes de la tarjeta
            javax.swing.JLabel lblNombre = new javax.swing.JLabel(nombre, javax.swing.SwingConstants.CENTER);
            lblNombre.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
            
            javax.swing.JLabel lblMarca = new javax.swing.JLabel("Marca: " + marca, javax.swing.SwingConstants.CENTER);
            javax.swing.JLabel lblPrecio = new javax.swing.JLabel("$" + precio, javax.swing.SwingConstants.CENTER);
            javax.swing.JLabel lblStock = new javax.swing.JLabel("Disponibles: " + stock, javax.swing.SwingConstants.CENTER);
            
            javax.swing.JButton btnAgregar = new javax.swing.JButton("Agregar al Carrito");
            
            //elementos de las tarjetas
            tarjeta.add(lblNombre);
            tarjeta.add(lblMarca);
            tarjeta.add(lblPrecio);
            tarjeta.add(lblStock);
            tarjeta.add(btnAgregar);
            // Metemos la tarjeta al contenedor principal
            pnlProductos.add(tarjeta);
            
            }
            //Refrescamos la interfaz para pintar los cambios
            pnlProductos.revalidate();
            pnlProductos.repaint();
        }catch (java.sql.SQLException e) {
        System.err.println("Error al cargar productos: " + e.getMessage());
    }
        
    }

    /**
     * Creates new form Menú
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BInicioSesion = new javax.swing.JButton();
        LBienvenida = new javax.swing.JLabel();
        PanelBarra = new javax.swing.JPanel();
        BVenta = new javax.swing.JButton();
        cbxCategorias = new javax.swing.JComboBox<>();
        BHamburguesa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlProductos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BInicioSesion.setText("Iniciar Sesión");
        BInicioSesion.addActionListener(this::BInicioSesionActionPerformed);

        LBienvenida.setText("jLabel2");

        PanelBarra.setBackground(new java.awt.Color(153, 153, 153));

        BVenta.setBackground(new java.awt.Color(153, 153, 153));
        BVenta.setText("Vender");
        BVenta.addActionListener(this::BVentaActionPerformed);

        cbxCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almacenamiento", "Bocinas", "Fuentes de poder", "Gabinetes", "Gráficas", "Microfonos", "Monitores", "Mouse", "RAM", "Procesadores", "Sillas", "Tarjetas madres", "Teclados", "Ventiladores (Gabinetes)" }));
        cbxCategorias.addActionListener(this::cbxCategoriasActionPerformed);

        javax.swing.GroupLayout PanelBarraLayout = new javax.swing.GroupLayout(PanelBarra);
        PanelBarra.setLayout(PanelBarraLayout);
        PanelBarraLayout.setHorizontalGroup(
            PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBarraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxCategorias, 0, 0, Short.MAX_VALUE)
                    .addGroup(PanelBarraLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BVenta)
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelBarraLayout.setVerticalGroup(
            PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarraLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cbxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(BVenta)
                .addGap(73, 73, 73))
        );

        BHamburguesa.setText("☰");
        BHamburguesa.addActionListener(this::BHamburguesaActionPerformed);

        jScrollPane1.setViewportView(pnlProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BHamburguesa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(LBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BInicioSesion)
                    .addComponent(LBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(BHamburguesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInicioSesionActionPerformed
        // TODO add your handling code here:
        //Instancia de ventana login con conexion
        Login VLogin = new Login(this.conexionActiva);
        //Abrimos ventana
        VLogin.setVisible(true);
        //codigo para centrar ventana en medio
        VLogin.setLocationRelativeTo(null);
        
        
        
    }//GEN-LAST:event_BInicioSesionActionPerformed

    private void BHamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHamburguesaActionPerformed
        // TODO add your handling code here:
        if (MenuDespegable){
            PanelBarra.setVisible(false);
            MenuDespegable = false;
        }else{
            PanelBarra.setVisible(true);
            MenuDespegable = true;
        }
    }//GEN-LAST:event_BHamburguesaActionPerformed

    private void BVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVentaActionPerformed
        // TODO add your handling code here:
        if (this.usuario){
            VPublicar ventanap = new VPublicar(this.conexionActiva);
                ventanap.setVisible(true);
                ventanap.setLocationRelativeTo(null); 
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Debes iniciar sesión para publicar y vender productos.");
            
            Login ventLogin = new Login (this.conexionActiva);
            ventLogin.setVisible(true);
            ventLogin.setLocationRelativeTo(null);
            
        }
        
        cargarProductos("Todas");
        
    }//GEN-LAST:event_BVentaActionPerformed

    private void cbxCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriasActionPerformed
        // TODO add your handling code here:
        //Obtenemos el nombre de la categoria que seleccione el usuario
        String categoriaSeleccionada = cbxCategorias.getSelectedItem().toString();
        
        //llamamos a cargarProductos para filtrar la categoria
        cargarProductos(categoriaSeleccionada);
    }//GEN-LAST:event_cbxCategoriasActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHamburguesa;
    private javax.swing.JButton BInicioSesion;
    private javax.swing.JButton BVenta;
    private javax.swing.JLabel LBienvenida;
    private javax.swing.JPanel PanelBarra;
    private javax.swing.JComboBox<String> cbxCategorias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlProductos;
    // End of variables declaration//GEN-END:variables
}
