/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carritocompras.Ventanas;

import java.sql.Connection;
import javax.swing.JFrame;

/**
 *
 * @author Arturo
 */
public class VCarrito extends javax.swing.JFrame {
    private java.sql.Connection conexionActiva;
    private int idUsuario;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VCarrito.class.getName());

    /**
     * Creates new form VCarrito
     */
    public VCarrito() {
        initComponents();
    }
    public VCarrito(java.sql.Connection conexion, int idUsuario) {
        initComponents();
        this.conexionActiva = conexion;
        this.idUsuario = idUsuario;
        // Carga los productos guardados en menu a la tabla
        cargarTablaCarrito();
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void cargarTablaCarrito() {
    // 1. Definir columnas para la tabla
    String[] columnas = {"Producto", "Precio Unitario", "Cantidad", "Subtotal"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);

    double totalGeneral = 0.0;

    // 2. Consulta SQL a PostgreSQL
    String sql = "SELECT p.nombre, p.precio, c.cantidad " +
                 "FROM carrito c " +
                 "JOIN productos p ON c.id_producto = p.id_productos " +
                 "WHERE c.id_usuario = ?";

    try {
        java.sql.PreparedStatement ps = this.conexionActiva.prepareStatement(sql);
        ps.setInt(1, this.idUsuario); // Lee los productos del usuario activo
        java.sql.ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            String nombre = rs.getString("nombre");
            double precio = rs.getDouble("precio");
            int cantidad = rs.getInt("cantidad");
            double subtotal = precio * cantidad;

            totalGeneral += subtotal;

            // Solo agregamos los datos del producto
            modelo.addRow(new Object[]{nombre, "$" + precio, cantidad, "$" + subtotal});
        }

        tblCarrito.setModel(modelo);
        lblTotal.setText("Total: $" + String.format("%.2f", totalGeneral));

    } catch (java.sql.SQLException e) {
        System.err.println("Error al cargar carrito: " + e.getMessage());
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnFinalizarCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCarrito);

        lblTotal.setText("Total: $0.00");

        btnFinalizarCompra.setText("Finalizar compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinalizarCompra)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizarCompra)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCarrito;
    // End of variables declaration//GEN-END:variables
}
