/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carritocompras.Ventanas;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Arturo
 */
public class VentanaRegistro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRegistro.class.getName());
    private final Connection conexionActiva;

    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistro(Connection conexion) {
        initComponents();
        this.conexionActiva = conexion;
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuariotxt = new javax.swing.JTextField();
        correotxt = new javax.swing.JTextField();
        contratxt = new javax.swing.JTextField();
        BCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BCrearCuenta.setText("Iniciar Sesión");
        BCrearCuenta.addActionListener(this::BCrearCuentaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuariotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(correotxt)
                    .addComponent(contratxt))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BCrearCuenta)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(usuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(correotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(contratxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BCrearCuenta)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCrearCuentaActionPerformed
        // TODO add your handling code here:
        String usuario = usuariotxt.getText().trim();
    String correo = correotxt.getText().trim();
    String contra = contratxt.getText().trim();

    // que no se dejen espacios en blanco
    if (usuario.isEmpty() || correo.isEmpty() || contra.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos.");
        return; // Detiene la ejecución para que no intente guardar cosas vacías
    }

    // Conectamos a la base de datos para hacer el insert
    String sql = "INSERT INTO usuarios (nombre_usuario, correo, contra_usuario) VALUES (?, ?, ?)";

    try {
        // Usamos la conexión activa que heredó esta ventana en el constructor
        java.sql.PreparedStatement ps = this.conexionActiva.prepareStatement(sql);
        ps.setString(1, usuario);
        ps.setString(2, correo);
        ps.setString(3, contra);

        // Ejecutamos el insert en la base de datos
        int resultado = ps.executeUpdate();

        if (resultado > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Cuenta creada con éxito!");

            // Lo regresamos automáticamente al Login
            Login ventanaLogin = new Login(this.conexionActiva);
            ventanaLogin.setVisible(true);
            ventanaLogin.setLocationRelativeTo(null);

            this.dispose(); // Cerramos la ventana de registro
        }
        //abre un panel de error
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar en PostgreSQL: " + e.getMessage());
    }

    }//GEN-LAST:event_BCrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCrearCuenta;
    private javax.swing.JTextField contratxt;
    private javax.swing.JTextField correotxt;
    private javax.swing.JTextField usuariotxt;
    // End of variables declaration//GEN-END:variables

}